RSS_SOURCES = {
    "Meduza": "https://meduza.io/rss/all",
    "ТАСС": "https://tass.ru/rss/v2.xml",
    "РБК": "https://rssexport.rbc.ru/rbcnews/news/30/full.rss",
    "Lenta.ru": "https://lenta.ru/rss/news",
    "Известия": "https://iz.ru/xml/rss/all.xml",
    "RT на русском": "https://russian.rt.com/rss",
    "Интерфакс": "https://www.interfax.ru/rss.asp",
    "РИА Новости": "https://ria.ru/export/rss2/archive/index.xml",
    "Коммерсантъ": "https://www.kommersant.ru/RSS/news.xml",
    "Ведомости": "https://www.vedomosti.ru/rss/news",
    "Новая газета": "https://novayagazeta.ru/rss/all.xml",
    "The Bell": "https://thebell.io/feed",
    "Московский комсомолец": "https://www.mk.ru/rss/news/index.xml",
    "Фонтанка": "https://www.fontanka.ru/fontanka.rss",
    "Знак": "https://www.znak.com/rss/news.xml",
    "360°": "https://360tv.ru/rss/all.xml",
    "Газета.Ru": "https://www.gazeta.ru/export/rss/lenta.xml",
    "BBC Russian": "http://feeds.bbci.co.uk/russian/rss.xml",
    "Deutsche Welle (рус)": "https://www.dw.com/ru/top-stories/s-9097?maca=rus-rss_rus_all-3272-rdf",
    "Sputnik": "https://sputniknews.ru/export/rss2/archive/index.xml",
    "REGNUM": "https://regnum.ru/rss/news.xml",
    "Радио Свобода": "https://www.svoboda.org/api/zrqiteuu$it",
    "Forbes Russia": "https://www.forbes.ru/rss.xml",
    "Snob": "https://snob.ru/feed/rss/",
    "ТВЦ": "https://www.tvc.ru/xml/rss.xml",
    "НТВ": "https://www.ntv.ru/novosti/rss/",
    "Life.ru": "https://life.ru/xml/rss.xml",
    "Newsru.com": "https://newsru.com/rss/allnews.xml",
    "Полит.ру": "https://polit.ru/rss.xml",
    "Обозреватель": "https://www.obozrevatel.com/rss.xml",
    "ИТАР-ТАСС Наука": "https://nauka.tass.ru/rss/v2.xml",
    "Хайтек+": "https://hi-tech.mail.ru/rss/all.xml",
    "VC.ru": "https://vc.ru/rss",
    "Rusbase": "https://rb.ru/rss/all/",
    "CNews": "https://www.cnews.ru/inc/rss/news.xml",
    "TJournal": "https://tjournal.ru/rss",
    "Durov's Channel": "https://telegra.ph/rss.xml",
    "Российская газета": "https://rg.ru/rss/all.xml",
    "Минобороны РФ": "https://function.mil.ru/news_page/country/rss.htm",
    "Минэкономразвития РФ": "https://economy.gov.ru/export/news/rss.xml",
    "Министерство науки и высшего образования": "https://minobrnauki.gov.ru/press-center/news/rss",
    "Минздрав РФ": "https://www.rosminzdrav.ru/news.rss",
    "Правительство РФ": "http://government.ru/rss/",
    "Госдума": "http://duma.gov.ru/rss/",
    "ЦИК России": "http://cikrf.ru/rss/news.rss",
    "Судебный департамент": "http://www.cdep.ru/rss.asp",
    "Росстат": "https://rosstat.gov.ru/rss",
    "Роскомнадзор": "https://rkn.gov.ru/rss",
    "Минцифры": "https://digital.gov.ru/ru/news/rss/",
    "МВД России": "https://xn--b1aew.xn--p1ai/news/rss/",
    "Следственный комитет": "https://sledcom.ru/rss.xml"
}